# Generated by Django 3.1.5 on 2021-01-13 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='Height of block')),
                ('hash_block', models.CharField(blank=True, max_length=200, verbose_name='Hash of block')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of block')),
                ('miner_address', models.CharField(blank=True, max_length=200, verbose_name='Miners addres')),
                ('num_of_transaction', models.PositiveIntegerField(null=True, verbose_name='Height of block')),
            ],
        ),
    ]
