# Generated by Django 3.1.5 on 2021-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC_core', '0002_auto_20210113_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='miner_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Miner addres'),
        ),
    ]
