# Generated by Django 3.1.5 on 2021-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BC_core', '0003_auto_20210116_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='hash_block',
        ),
    ]
