# Generated by Django 3.1.5 on 2021-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BC_core', '0004_remove_block_hash_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hash_block',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hash of block'),
        ),
    ]
